github install czxa/dict, replace
local colorstyle "color-白茶.style ///
color-白绿.style ///
color-白橡.style ///
color-百草霜.style ///
color-百茶.style ///
color-柏坊灰蓝.style ///
color-薄红.style ///
color-薄青.style ///
color-薄柿.style ///
color-薄香.style ///
color-宝蓝.style ///
color-北京毛蓝.style ///
color-碧玉石.style ///
color-柄.style ///
color-菜花.style ///
color-菜籽油.style ///
color-苍黄.style ///
color-苍绿.style ///
color-藏蓝.style ///
color-草黄.style ///
color-常磐.style ///
color-辰砂.style ///
color-承德灰.style ///
color-承德皂.style ///
color-赤白象.style ///
color-赤红.style ///
color-赤香.style ///
color-赤朽.style ///
color-春蓝.style ///
color-春绿.style ///
color-粗晶皂.style ///
color-翠绿.style ///
color-大赤金.style ///
color-代赭.style ///
color-黛蓝.style ///
color-丹东石.style ///
color-淡灰绿.style ///
color-灯草灰.style ///
color-砥粉.style ///
color-靛蓝.style ///
color-丁子茶.style ///
color-丁子染.style ///
color-法染.style ///
color-蕃茄红.style ///
color-妃红.style ///
color-绯.style ///
color-肥后煤竹.style ///
color-粉红.style ///
color-抚子.style ///
color-甘草黄.style ///
color-甘石粉.style ///
color-橄榄绿.style ///
color-钴蓝.style ///
color-桂皮.style ///
color-桧皮.style ///
color-果灰.style ///
color-裹柳.style ///
color-海蓝.style ///
color-海老茶.style ///
color-海松.style ///
color-海松茶.style ///
color-韩红花.style ///
color-红.style ///
color-红绯.style ///
color-红孤.style ///
color-红桧皮.style ///
color-红桦.style ///
color-红金.style ///
color-红梅.style ///
color-红鸢.style ///
color-红皂.style ///
color-狐.style ///
color-胡粉.style ///
color-胡桃.style ///
color-琥珀.style ///
color-花青.style ///
color-桦.style ///
color-桦茶.style ///
color-黄丹.style ///
color-黄海松茶.style ///
color-黄花.style ///
color-黄灰.style ///
color-黄蘖.style ///
color-黄染.style ///
color-黄糖茶.style ///
color-黄土.style ///
color-黄橡.style ///
color-黄朽.style ///
color-灰蓝.style ///
color-灰楼.style ///
color-灰绿.style ///
color-灰米.style ///
color-灰汁.style ///
color-伽罗.style ///
color-茄皮紫.style ///
color-煎茶.style ///
color-江户茶.style ///
color-姜黄.style ///
color-将校呢.style ///
color-绛紫.style ///
color-酱色.style ///
color-焦茶.style ///
color-芥子.style ///
color-金茶.style ///
color-金黄.style ///
color-鞠鹿.style ///
color-桔红.style ///
color-桔黄.style ///
color-军绿.style ///
color-卡其黄.style ///
color-卡其绿.style ///
color-孔雀蓝.style ///
color-枯绿.style ///
color-库金.style ///
color-蜡白.style ///
color-蓝媚茶.style ///
color-老绿.style ///
color-老竹.style ///
color-璃宽茶.style ///
color-里鸢.style ///
color-利休白茶.style ///
color-利休茶.style ///
color-栗梅.style ///
color-栗皮茶.style ///
color-令样.style ///
color-琉璃.style ///
color-榴花红.style ///
color-柳茶.style ///
color-柳煤竹.style ///
color-柳染.style ///
color-柳鼠.style ///
color-楼鼠.style ///
color-芦灰.style ///
color-栌染.style ///
color-鹿金.style ///
color-路考茶.style ///
color-绿.style ///
color-绿青.style ///
color-玫瑰红.style ///
color-玫瑰灰.style ///
color-莓.style ///
color-梅染.style ///
color-梅鼠.style ///
color-梅幸茶.style ///
color-煤竹.style ///
color-媚茶.style ///
color-萌黄.style ///
color-米红.style ///
color-米灰.style ///
color-米色.style ///
color-苗.style ///
color-木賊.style ///
color-奶绿.style ///
color-奶棕.style ///
color-柠檬黄.style ///
color-女郎花.style ///
color-枇杷茶.style ///
color-品红.style ///
color-千岁茶.style ///
color-千岁绿.style ///
color-牵牛紫.style ///
color-铅丹.style ///
color-浅海昌蓝.style ///
color-浅红.style ///
color-浅黄.style ///
color-浅黄棕.style ///
color-浅桔黄.style ///
color-浅石英紫.style ///
color-浅藤紫.style ///
color-浅驼色.style ///
color-浅血牙.style ///
color-浅棕灰.style ///
color-青磁.style ///
color-青丹.style ///
color-青朽.style ///
color-雀茶.style ///
color-鹊灰.style ///
color-绒蓝.style ///
color-若竹.style ///
color-鶸.style ///
color-鶸茶.style ///
color-鶸萌黄.style ///
color-洒落柿.style ///
color-三绿.style ///
color-桑茶.style ///
color-桑染.style ///
color-沙绿.style ///
color-沙青.style ///
color-山吹.style ///
color-山吹茶.style ///
color-珊瑚朱.style ///
color-深绯.style ///
color-深烟.style ///
color-深烟红.style ///
color-深支子.style ///
color-深竹月.style ///
color-甚三红.style ///
color-生壁.style ///
color-十样锦.style ///
color-柿.style ///
color-曙.style ///
color-水貂灰.style ///
color-水黄.style ///
color-水棕.style ///
color-松.style ///
color-宋.style ///
color-苏芳.style ///
color-苏芳香.style ///
color-苔.style ///
color-唐茶.style ///
color-桃.style ///
color-藤黄.style ///
color-天青.style ///
color-铁灰.style ///
color-土黄.style ///
color-退红.style ///
color-万茶.style ///
color-乌子.style ///
color-洗柿.style ///
color-洗朱.style ///
color-相思灰.style ///
color-小豆.style ///
color-猩红.style ///
color-猩猩绯.style ///
color-雄黄.style ///
color-雄精.style ///
color-朽.style ///
color-锈红.style ///
color-锈绿.style ///
color-萱草.style ///
color-选金.style ///
color-雪色.style ///
color-雪紫.style ///
color-血红.style ///
color-薰.style ///
color-鸭蛋青.style ///
color-胭脂.style ///
color-岩井茶.style ///
color-艳红.style ///
color-燕脂.style ///
color-洋葱紫.style ///
color-洋红.style ///
color-一斥染.style ///
color-刈安.style ///
color-银箔.style ///
color-银煤竹.style ///
color-银朱.style ///
color-鹦鹉绿.style ///
color-油绿.style ///
color-油烟墨.style ///
color-玉石蓝.style ///
color-玉蜀黍.style ///
color-玉子.style ///
color-御纳户茶.style ///
color-鸢.style ///
color-鸳.style ///
color-鸳茶.style ///
color-元青.style ///
color-远州茶.style ///
color-月季红.style ///
color-枣红.style ///
color-章丹.style ///
color-长春.style ///
color-照柿.style ///
color-真朱.style ///
color-蒸栗.style ///
color-正灰.style ///
color-芝茶.style ///
color-枝黄.style ///
color-织锦灰.style ///
color-栀子.style ///
color-纸棕.style ///
color-中红.style ///
color-中棕灰.style ///
color-紫粉.style ///
color-紫染.style ///
color-紫水晶.style ///
color-紫藤灰.style ///
color-紫薇花.style ///
color-宗传唐茶.style ///
color-棕茶.style"
foreach i in `colorstyle'{
	percentencode `i'
	copy "https://github.com/czxa/stcolor/raw/master/colorstyle/`r(percentencode)'" "`c(sysdir_plus)'/style/`i'", replace
}
